name = "ImageClassification"
uuid = "94ff7110-d6ac-48b2-8417-2b0ab2331c97"
version = "0.0.1"
authors = ["ornellavolle <ornellavolle@gmail.com>"]

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLJFlux = "094fc8d1-fd35-5302-93ea-dabda2abf845"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Bonito = "4.1.11"
FileIO = "1.17.1"
Flux = "0.16.5"
Glob = "1.3.1"
ImageIO = "0.6.9"
ImageTransformations = "0.10.2"
Images = "0.26.2"
Lux = "1.21.1"
MLJFlux = "0.6.7"
MLUtils = "0.4.8"
OneHotArrays = "0.2.10"
Optimisers = "0.4.6"
Random = "1.11.0"
Statistics = "1.11.1"
WGLMakie = "0.13.6"
Zygote = "0.7.10"
julia = "1.10"
