name = "ImageClassification"
uuid = "94ff7110-d6ac-48b2-8417-2b0ab2331c97"
version = "0.0.1"
authors = ["ornellavolle <ornellavolle@gmail.com>"]

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
MLJFlux = "094fc8d1-fd35-5302-93ea-dabda2abf845"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ComponentArrays = "0.15.30"
FileIO = "1.17.1"
FilePathsBase = "0.9.24"
Flux = "0.16.5"
Glob = "1.3.1"
ImageIO = "0.6.9"
ImageTransformations = "0.10.2"
Images = "0.26.2"
Lux = "1.21.1"
LuxCUDA = "0.3.4"
MLUtils = "0.4.8"
OneHotArrays = "0.2.10"
Optimisers = "0.4.6"
OrdinaryDiffEq = "6.101.0"
OrdinaryDiffEqTsit5 = "1.5.0"
MLJFlux = "0.6.7"
Random = "1.11.0"
SciMLSensitivity = "7.90.0"
Statistics = "1.11.1"
Zygote = "0.7.10"
julia = "1.10"
